src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     * @ORM\Id
     *
     * @ORM\GeneratedValue
     *
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $name;

    /**
     * @ORM\OneToMany(targetEntity=Player::class, mappedBy="user", orphanRemoval=true)
     */
    private Collection $players;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $token;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $alias;

    public function __construct()
    {
        $this->players = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Player>
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    /**
     * @return $this
     */
    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
            $player->setUser($this);
        }

        return $this;
    }

    /**
     * @return $this
     */
    public function removePlayer(Player $player): self
    {
        if ($this->players->removeElement($player)) {
            // set the owning side to null (unless already changed)
            if ($player->getUser() === $this) {
                $player->setUser(null);
            }
        }

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * @return $this
     */
    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @return $this
     */
    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias ?: $this->getName();
    }

    /**
     * @return $this
     */
    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getScoreTotal(): int
    {
        $score = 0;

        /** @var Player $player */
        foreach ($this->getPlayers() as $player) {
            if ($player->getGame()->getIsOver()) {
                $score += $player->getScore();
            }
        }

        return $score;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\YamsController;
use Symfony\Component\HttpFoundation\Response;

class UserController extends YamsController
{
    /**
     * Liste des users.
     */
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $this->userService->getUsers(),
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   <div class="row">
      <div class="col-6">
         <a href="{{ path('index') }}" class="js-openLoader">
            <div class="box pushed-touch">
               <div class="box-body p10 text-center">
                  <div class="bold">Retour</div>
               </div>
            </div>
         </a>
      </div>
      <div class="col-6">
         <a href="{{ path('game_index') }}" class="js-openLoader">
            <div class="box pushed-touch">
               <div class="box-body p10 text-center">
                  <div class="bold">Jouer</div>
               </div>
            </div>
         </a>
      </div>
   </div>

   <div class="hr"></div>

   <div class="row">
      {% for k, user in users %}
         <div class="col-6 col-sm-4">
            <div class="box {{ loop.last ? 'mb0' : '' }} text-center">
               <div class="box-body">
                  <div>
                     <img src="{{ asset('img/avatar/' ~ user.image) }}" class="avatar h100">
                  </div>
                  <div>
                     <div class="bold fs16 mt10">{{ user.name }}</div>
                     <div class="fs13 color-9">{{ user.scoreTotal|score }}</div>
                  </div>
                  <div class="clear"></div>
               </div>
            </div>
         </div>
      {% endfor %}
   </div>
{% endblock %}